// Action Types

// Auth
export const AUTH_LOADING  = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Apps
export const FETCH_APPS_LOADING = 'FETCH_APPS_LOADING';
export const FETCH_APPS_SUCCESS = 'FETCH_APPS_LOADING_SUCCESS';
export const FETCH_APPS_FAILED = 'FETCH_APPS_LOADING_FAILED';
export const CHANGE_APPS_FILTER = 'CHANGE_APPS_FILTER';